server:
  port: 1234
  servlet:
    context-path: /app
  error:
    whitelabel:
      enabled: false
---
spring:
  profiles: dev
  aop:
    proxy-target-class: true
  http:
    encoding:
      charset: UTF-8
  datasource:
    data: classpath:data.sql
    schema: classpath:schema.sql
    url: jdbc:mysql://localhost:3306/angular
    username: root
    password: root
    druid:
      name: local-mysql
#     初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      initial-size: 3
#     最大连接池数量
#     最小连接池数量
      min-idle: 1
#     获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
      max-wait: 100
#     是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      pool-prepared-statements: true
#     要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      max-pool-prepared-statement-per-connection-size: 100
#     要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      time-between-eviction-runs-millis: 60000
      validation-query: select 1
#     单位：秒，检测连接是否有效的超时时间。底层调用jdbc Statement对象的void setQueryTimeout(int seconds)方法
      validation-query-timeout: 500
#     建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
#     申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-borrow: false
#     归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false
#     连接保持空闲而不被驱逐的最长时间
      min-evictable-idle-time-millis: 40000
      use-global-data-source-stat: true
      connection-properties: config.decrypt=false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: -*.js -*.gif -*.jpg -*.bmp -*.png -*.css -*.ico -/druid/*
        session-stat-enable: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: druid
        login-password: druid
        allow: 127.0.0.1
        deny:
      filter:
        config:
          enabled: true
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          connection-stack-trace-enable: false
          merge-sql: true
        wall:
          enabled: true
          db-type: mysql
      max-active: 10
      aop-patterns: com.demo.*
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    mode: LEGACYHTML5
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    enabled: true

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.demo.angularpractice.entity
  configuration:
    log-prefix: mybatis_
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: true
    default-executor-type: simple
    default-statement-timeout: 25000
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    use-actual-param-name: true
  configuration-properties:
    logImpl: SLF4J


pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
mapper:
  mappers: tk.mybatis.springboot.util.MyMapper
  not-empty: false
  identity: MYSQL
debug: false
logging:
  level:
    root: info


# 数据库连接池
---
spring:
  profiles: prod



