server:
  port: 1234
  servlet:
    context-path: /app
    session:
      persistent: true
      timeout: 6000s
  error:
    whitelabel:
      enabled: false
---
spring:
  profiles: dev
  aop:
    proxy-target-class: true
  http:
    encoding:
      charset: UTF-8
  datasource:
    data: classpath:data.sql
    schema: classpath:schema.sql
    url: jdbc:mysql://localhost:3306/angular
    username: root
    password: root
    druid:
      name: local-mysql
#     初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
      initial-size: 3
#     最大连接池数量
#     最小连接池数量
      min-idle: 1
#     获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
      max-wait: 100
#     是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      pool-prepared-statements: true
#     要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      max-pool-prepared-statement-per-connection-size: 100
#     要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      time-between-eviction-runs-millis: 60000
      validation-query: select 1
#     单位：秒，检测连接是否有效的超时时间。底层调用jdbc Statement对象的void setQueryTimeout(int seconds)方法
      validation-query-timeout: 500
#     建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
#     申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-borrow: false
#     归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false
#     连接保持空闲而不被驱逐的最长时间
      min-evictable-idle-time-millis: 40000
      use-global-data-source-stat: true
      connection-properties: config.decrypt=false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: -*.js -*.gif -*.jpg -*.bmp -*.png -*.css -*.ico -/druid/*
        session-stat-enable: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: druid
        login-password: druid
        allow: 127.0.0.1
        deny:
      filter:
        config:
          enabled: true
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          connection-stack-trace-enable: false
          merge-sql: true
        wall:
          enabled: true
          db-type: mysql
      max-active: 10
      aop-patterns: com.demo.*
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    mode: LEGACYHTML5
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    enabled: true
#  kafka:
#    consumer:
#      auto-offset-reset: latest
#      group-id: foo
  cache:
    type: redis
    redis:
      key-prefix: spring_boot_
      use-key-prefix: true
      cache-null-values: false
      time-to-live: 6000s
  data:
    redis:
      repositories:
        enabled: true
  redis:
    database: 0
    host: localhost
    jedis:
      pool:
        max-active: 20
        max-idle: 8
        max-wait: 1000ms
        min-idle: 1
    port: 6379
    timeout: 2000ms
    password:
#  session:
#    redis:
#      flush-mode: IMMEDIATE
#      namespace: spring_session
#      cleanup-cron: 0 * * * * *
#    store-type: redis
#  activemq:
#      user: admin
#      password: admin
#      in-memory: false
#      broker-url: tcp://localhost:61616
#      close-timeout: 15s
#      pool:
#        enabled: false
#        max-connections: 2
#        # 请求和连接池满时，抛异常
#        block-if-full: true
#        # 抛异常前等待时间
#        block-if-full-timeout: -1ms
#        create-connection-on-startup: true
#        # 连接过期超时
#        expiry-timeout: 0ms
#        # 连接空闲超时
#        idle-timeout: 30s
#        # 每个连接的有效会话的最大数目
#        maximum-active-session-per-connection: 100
#        # 有异常时尝试重新连接
#        reconnect-on-exception: true
#        # 在空闲连接清除线程之间运行的时间。当为负数时，没有空闲连接驱逐线程运行
#        time-between-expiration-check: -1ms
#
#      # 等待消息发送响应的时间，0为永远等待
#      send-timeout: 3s
#      # 消息回滚之前停止消息传递，启用时，将不会保留顺序
#      non-blocking-redelivery: false
#      packages:
#      # 信任所有的包
#        trust-all: true
  mail:
    default-encoding: utf-8
    protocol: smtp
    host: smtp.qq.com
    password: vippzavknlepbgff
    port: 587
    test-connection: true
    username: 164408623@qq.com
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.demo.angularpractice.entity
  configuration:
    log-prefix: mybatis_
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: true
    default-executor-type: simple
    default-statement-timeout: 25000
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    use-actual-param-name: true
  configuration-properties:
    logImpl: SLF4J

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
debug: true
logging:
  level:
    root: info

# 数据库连接池
---
spring:
  profiles: prod